// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OpenWeather.ApiClient.Demo.Weather
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    #pragma warning disable CS1591
    public enum GetLangQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ar")]
        #pragma warning disable CS1591
        Ar,
        #pragma warning restore CS1591
        [EnumMember(Value = "bg")]
        #pragma warning disable CS1591
        Bg,
        #pragma warning restore CS1591
        [EnumMember(Value = "ca")]
        #pragma warning disable CS1591
        Ca,
        #pragma warning restore CS1591
        [EnumMember(Value = "cz")]
        #pragma warning disable CS1591
        Cz,
        #pragma warning restore CS1591
        [EnumMember(Value = "de")]
        #pragma warning disable CS1591
        De,
        #pragma warning restore CS1591
        [EnumMember(Value = "el")]
        #pragma warning disable CS1591
        El,
        #pragma warning restore CS1591
        [EnumMember(Value = "en")]
        #pragma warning disable CS1591
        En,
        #pragma warning restore CS1591
        [EnumMember(Value = "fa")]
        #pragma warning disable CS1591
        Fa,
        #pragma warning restore CS1591
        [EnumMember(Value = "fi")]
        #pragma warning disable CS1591
        Fi,
        #pragma warning restore CS1591
        [EnumMember(Value = "fr")]
        #pragma warning disable CS1591
        Fr,
        #pragma warning restore CS1591
        [EnumMember(Value = "gl")]
        #pragma warning disable CS1591
        Gl,
        #pragma warning restore CS1591
        [EnumMember(Value = "hr")]
        #pragma warning disable CS1591
        Hr,
        #pragma warning restore CS1591
        [EnumMember(Value = "hu")]
        #pragma warning disable CS1591
        Hu,
        #pragma warning restore CS1591
        [EnumMember(Value = "it")]
        #pragma warning disable CS1591
        It,
        #pragma warning restore CS1591
        [EnumMember(Value = "ja")]
        #pragma warning disable CS1591
        Ja,
        #pragma warning restore CS1591
        [EnumMember(Value = "kr")]
        #pragma warning disable CS1591
        Kr,
        #pragma warning restore CS1591
        [EnumMember(Value = "la")]
        #pragma warning disable CS1591
        La,
        #pragma warning restore CS1591
        [EnumMember(Value = "lt")]
        #pragma warning disable CS1591
        Lt,
        #pragma warning restore CS1591
        [EnumMember(Value = "mk")]
        #pragma warning disable CS1591
        Mk,
        #pragma warning restore CS1591
        [EnumMember(Value = "nl")]
        #pragma warning disable CS1591
        Nl,
        #pragma warning restore CS1591
        [EnumMember(Value = "pl")]
        #pragma warning disable CS1591
        Pl,
        #pragma warning restore CS1591
        [EnumMember(Value = "pt")]
        #pragma warning disable CS1591
        Pt,
        #pragma warning restore CS1591
        [EnumMember(Value = "ro")]
        #pragma warning disable CS1591
        Ro,
        #pragma warning restore CS1591
        [EnumMember(Value = "ru")]
        #pragma warning disable CS1591
        Ru,
        #pragma warning restore CS1591
        [EnumMember(Value = "se")]
        #pragma warning disable CS1591
        Se,
        #pragma warning restore CS1591
        [EnumMember(Value = "sk")]
        #pragma warning disable CS1591
        Sk,
        #pragma warning restore CS1591
        [EnumMember(Value = "sl")]
        #pragma warning disable CS1591
        Sl,
        #pragma warning restore CS1591
        [EnumMember(Value = "es")]
        #pragma warning disable CS1591
        Es,
        #pragma warning restore CS1591
        [EnumMember(Value = "tr")]
        #pragma warning disable CS1591
        Tr,
        #pragma warning restore CS1591
        [EnumMember(Value = "ua")]
        #pragma warning disable CS1591
        Ua,
        #pragma warning restore CS1591
        [EnumMember(Value = "vi")]
        #pragma warning disable CS1591
        Vi,
        #pragma warning restore CS1591
        [EnumMember(Value = "zh_cn")]
        #pragma warning disable CS1591
        Zh_cn,
        #pragma warning restore CS1591
        [EnumMember(Value = "zh_tw")]
        #pragma warning disable CS1591
        Zh_tw,
        #pragma warning restore CS1591
    }
}
