// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OpenWeather.ApiClient.Demo.Weather
{
    #pragma warning disable CS1591
    public enum GetModeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "json")]
        #pragma warning disable CS1591
        Json,
        #pragma warning restore CS1591
        [EnumMember(Value = "xml")]
        #pragma warning disable CS1591
        Xml,
        #pragma warning restore CS1591
        [EnumMember(Value = "html")]
        #pragma warning disable CS1591
        Html,
        #pragma warning restore CS1591
    }
}
