// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OpenWeather.ApiClient.Demo.Weather
{
    #pragma warning disable CS1591
    public enum GetUnitsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "standard")]
        #pragma warning disable CS1591
        Standard,
        #pragma warning restore CS1591
        [EnumMember(Value = "metric")]
        #pragma warning disable CS1591
        Metric,
        #pragma warning restore CS1591
        [EnumMember(Value = "imperial")]
        #pragma warning disable CS1591
        Imperial,
        #pragma warning restore CS1591
    }
}
